epan: restore removal of errno.h
epan/ftypes/ftype-bytes.c:181:3: error: ‘errno’ undeclared (first use in
this function)
   errno = 0;
   ^~~~~

removed in 3c3165f5