btbredr_rf: fix a warning
```
/home/ivan/svnrepos/wireshark/epan/dissectors/packet-btbredr_rf.c: In function ‘dissect_btbredr_rf’:
/home/ivan/svnrepos/wireshark/epan/dissectors/packet-btbredr_rf.c:972:8: error: ‘ltaddr’ may be used uninitialized [-Werror=maybe-uninitialized]
  972 |     if (header_mode > 0 && ltaddr)
      |        ^
/home/ivan/svnrepos/wireshark/epan/dissectors/packet-btbredr_rf.c:665:27: note: ‘ltaddr’ was declared here
  665 |     uint32_t              ltaddr;
      |                           ^~~~~~
cc1: all warnings being treated as errors
```


(cherry picked from commit 1a5f3fad000a446c32858344fb9f952f7f29794c)

Co-authored-by: Ivan Nardi <nardi.ivan@gmail.com>