ieee80211: Eliminate false positive maybe-initialized
I found a set of compiler flags that lead to this false positive from
inlining:

In function ‘add_ff_eht_mu_exclusive_80MHz_rpt’,
    inlined from ‘add_ff_eht_mu_exclusive_beamforming_rpt.isra’ at /home/johnthacker/wireshark/epan/dissectors/packet-ieee80211.c:17661:16:
/home/johnthacker/wireshark/epan/dissectors/packet-ieee80211.c:17384:17: error: ‘snr’ may be used uninitialized [-Werror=maybe-uninitialized]
17384 |           value = snr >> 4;
      |           ~~~~~~^~~~~~~~~~
/home/johnthacker/wireshark/epan/dissectors/packet-ieee80211.c: In function ‘add_ff_eht_mu_exclusive_beamforming_rpt.isra’:
/home/johnthacker/wireshark/epan/dissectors/packet-ieee80211.c:17330:10: note: ‘snr’ was declared here
17330 |   int8_t snr, value;

This can't happen because get_snr is always initialized to 1, and snr is
retrieved in that case, but quiet this warning anyway.