isdn-sup: Properly register dissectors
Clang 17 correctly warns about this code, which has been wrong
for a decade.

wireshark/epan/dissectors/packet-isdn-sup.c:2944:5: error: code will never be executed [-Werror,-Wunreachable-code]
 2944 |                   dissector_add_string("q932.ros.global.res", isdn_sup_global_op_tab[i].oid, create_dissector_handle(isdn_sup_global_op_tab[i].res_pdu, proto_isdn_sup));
      |                   ^~~~~~~~~~~~~~~~~~~~
1 error generated.

Fix #19477