wsutil/CMakeLists: add missing array.h
Fix array.h missing in debian packaging:
  In file included from debian/headers-check.c:14:
  debian/libwireshark-dev/usr/include/wireshark/epan/packet.h:15:10: fatal error: wsutil/array.h: No such file or directory