pidl: Cherry-pick commits from upstream Samba
Squash cherry-pick commits from upstream Samba. Ping #15408. [skip ci]

    commit c6981f60549c497d401c4c4173dc362f083791d7 (squashed)
    Author: Andrew Bartlett <abartlet@samba.org>
    Date:   Wed Mar 29 11:49:43 2023 +1300

        librpc/ndr: Make ndr_push_compression_state_free() a talloc destructor

        This means that the generic_mszip_free() will still be called on failure.

        Signed-off-by: Andrew Bartlett <abartlet@samba.org>
        Reviewed-by: Douglas Bagnall <douglas.bagnall@catalyst.net.nz>

    commit 0ef71cf1524e855b0ae17051b054ef27d1c95717
    Author: Andrew Bartlett <abartlet@samba.org>
    Date:   Wed Mar 29 11:43:10 2023 +1300

        pidl: Automatically manage creating and freeing the compression state in generated code

        Manually written code will handle this differently, but for generated code
        this will create and free the context.

        Signed-off-by: Andrew Bartlett <abartlet@samba.org>
        Reviewed-by: Douglas Bagnall <douglas.bagnall@catalyst.net.nz>

    commit b95117dc56e185c8825752b1129ac704f832ce04
    Author: Andrew Bartlett <abartlet@samba.org>
    Date:   Tue Mar 28 18:31:45 2023 +1300

        libndr/ndr: Remove unused argument from ndr_push_compression_{start,end}()

        Removing the unused arguments avoids thier value being calculated in the
        PIDL generated code, which can be expensive.

        Signed-off-by: Andrew Bartlett <abartlet@samba.org>
        Reviewed-by: Douglas Bagnall <douglas.bagnall@catalyst.net.nz>

    commit 976dfc7585fcce594f5e77c8bb8ccc9644625f95
    Author: Andrew Bartlett <abartlet@samba.org>
    Date:   Fri Mar 24 15:00:33 2023 +1300

        pidl: Allow variable expansion (eg of a value() attribute) in compression_alg argument

        Signed-off-by: Andrew Bartlett <abartlet@samba.org>
        Reviewed-by: Douglas Bagnall <douglas.bagnall@catalyst.net.nz>

    commit e26a01a48c4a6ca6f9424ced72eda68e6eb1e7e3
    Author: Douglas Bagnall <douglas.bagnall@catalyst.net.nz>
    Date:   Fri Dec 9 10:36:30 2022 +1300

        pidl: avoid py compile issues with --pidl-developer

        We get these warnings-as-errors:

        librpc/gen_ndr/py_netlogon.c:61903:53: error: stray ‘\’ in program
        61903 |    PyErr_Format(PyExc_TypeError, "Expected type %s",\  //<PIDL> Parse::Pidl::Samba4::Python::ConvertObjectFromPythonData  lib/Parse/Pidl/Samba4/Python.pm:2005

        but the '\' is unnecessary and unconventional anyway, since we're in a
        function argument list.

        Signed-off-by: Douglas Bagnall <douglas.bagnall@catalyst.net.nz>
        Reviewed-by: Andrew Bartlett <abartlet@samba.org>

        Autobuild-User(master): Andrew Bartlett <abartlet@samba.org>
        Autobuild-Date(master): Fri Feb  3 03:27:54 UTC 2023 on atb-devel-224