tls-util: fix an "unused-but-set-variable" warning
This warning is triggered when compiling without Kerberos support, i.e.
with `-DENABLE_KERBEROS=OFF` flag:

```
../epan/dissectors/packet-tls-utils.c:9416:17: error: variable 'certificate_index' set but not used [-Werror,-Wunused-but-set-variable]
    guint       certificate_index = 0;
                ^
1 error generated.
```