dfilter: Don't crash on arithmetic between string literals
Don't assert that we can't get to the arithmetic check with
a string literal node.

Instead of:

./run/dftest -s 'http.host == "host" + ".com"'
Filter:
 http.host == "host" + ".com"

 ** (dftest:389225) 19:51:58.295340 [DFilter ERROR] epan/dfilter/semcheck.c:2078 -- check_arithmetic(): Invalid syntax node type 'STRING'.
 ** (dftest:389225) Aborting on fatal log level exception
Aborted (core dumped)

$ ./run/dftest -s 'http.host == "host" + ".com"'
Filter:
 http.host == "host" + ".com"

Error: FT_STRING cannot be added.
  http.host == "host" + ".com"

Perhaps in the future we could support the addition operator with
string, to mean concatenation?